require: rubocop-jekyll
inherit_gem:
  rubocop-jekyll: .rubocop.yml

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: no_mixed_keys
  